### ISSUE TITLE
Data Source SQL to PostgreSQL problem

### ISSUE THREAD

**Issue by JRRedigolo** [SCADA-LTS/Scada-LTS#2367]
We are using version 1.1. In our application we use SQL datasources to communicate with a Postgresql database. It happens that ScadaBR opens a connection with the bank in the first query and does not close it anymore. This causes a serious problem in the database that limits the number of open connections (default : 100 connections). When this number is reached, the bank starts to ignore the next queries, causing errors in the data visualization. We ask if it is not possible to add a mechanism to close the connection as soon as the query is performed, reopening it in the next query?
Thank you very much!

**Comment by Limraj** [comment]
Hello,
we will check it and try to fix it in version 2.7.3.

**Comment by JRRedigolo** [comment]
Thank you!!!

**Comment by Limraj** [comment]
Hi @JRRedigolo ,
we are dealing with this problem right now.
Could you please post an example configuration of one such Data Source with points? Of course without real ports/user/passwords etc.

This data source can be used in various ways, it is worth checking the specific scenario.

To generate this configuration:
1. Go to "Import/Export";
2. In the "Export" section, check the following checkboxes: Data Sources and Data Points;
3. Click on the "Generate JSON" button;
4. Copy json to notepad, edit text, leave specific Data Source and Data Point, change sensitive data and save;
5. Zip the text file with the configuration and attach it here.

**Comment by JRRedigolo** [comment]
Hello Kamil, good evening!

We are using version 1.1. We are now starting the migration to the latest stable version of the LTS, but the company we hired has a full schedule and still hasn't answered us. Would you like to receive the requested file even if it is version 1.1, or is it better to wait for the migration?

 

 

Atenciosamente,

 


 

José Roberto Redígolo

Diretor

*: 16 3618-5088  Cel: 16 98106-3737

* ***@***.***> ***@***.***


Nada é tão urgente que não possa ser feito com qualidade.

Esta mensagem contém informação confidencial e legalmente protegida aos seus destinatários. Se você não for uma destas pessoas, ou a tiver recebido por engano. fica desde já notificado de abster-se de divulgar, copiar, distribuir, examinar ou, de qualquer forma, utilizar a informação nela contida, por ser ilegal. Neste caso, solicita-se avisar imediatamente o remetente para as devidas providencias.

 

De: Kamil Jarmusik ***@***.***> 
Enviada em: terça-feira, 15 de novembro de 2022 13:58
Para: SCADA-LTS/Scada-LTS ***@***.***>
Cc: JRRedigolo ***@***.***>; Mention ***@***.***>
Assunto: Re: [SCADA-LTS/Scada-LTS] Data Source SQL to PostgreSQL problem (Issue #2367)

 

Hi @JRRedigolo <https://github.com/JRRedigolo>  ,
we are dealing with this problem right now.
Could you please post an example configuration of one such Data Source with points? Of course without real ports/user/passwords etc.

This data source can be used in various ways, it is worth checking the specific scenario.

To generate this configuration:

1.	Go to "Import/Export";
2.	In the "Export" section, check the following checkboxes: Data Sources and Data Points;
3.	Click on the "Generate JSON" button;
4.	Copy json to notepad, edit text, leave specific Data Source and Data Point, change sensitive data and save;
5.	Zip the text file with the configuration and attach it here.

**Comment by Limraj** [comment]
Hi,
I mean an example SQL Data Source configuration that you use and which causes problems, i.e. one such Data Source with at least one point, but you must remember not to send sensitive data, ports, etc.

**Comment by Limraj** [comment]
4. If you use this production base in one application (ScadaBR 1.1) You can still consider configuring connections in the server itself. This means that the server itself closes unused connections. For example, in MySQL you can set it by changing the 'wait_timeout' parameter, the unit is seconds. There is also a 'max_connections' parameter in MySQL. Both of these parameters could stabilize the configurator on your code version. (ScadaBR 1.1)

**Comment by Limraj** [comment]
Hello @JRRedigolo 
We have pre-released 2.7.3, remember that the difference between versions is several years, so you need solid testing, on production data, outside of the production environment.

When it comes to configuring Data Source SQL based on a resource available via JNDI (we recommend this configuration):
1. First you need to create such resource in tomcat configuration. This is defined in the Context tag, via Resource tag, similarly to how the main database is configured, it is contained in the file:
CATALINA_HOME/conf/context.xml

2. The second step is after starting Tomcat with the new configuration, then just copy the Resource name (attribute name in Resource tag) and move it to the Data Source SQL definition in Scada-LTS (set checkbox "JNDI Resource", past Resource name and click save). You can immediately test whether the connection to the database is working.

Of course, if there are any problems, we are here to help, it will be a valuable experience for us.

Best wishes,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hello, the fix is ​​in version 2.7.3. I close the topic.

**Comment by fabiodurao** [comment]
Hello,

I'm testing the JNDI resource a lot, in short I migrated the JRRedigolo server from ScadaBR 1.1 to Scada-LTS v2.7.4.1 and we have 85 SQL datasources, all are connecting to the same DB, they are just different SELECT's in each DataSource, it has improved a lot the question of the number of connections, but there were still some questions.

1 - I based myself on the context.xml resource to replicate the connection to the JNDI, as explained, I would like to understand how I can manipulate the parameters to reduce the number of connections, from what I understand, the parameters that interest me would be
           maxActive="80"
           minIdle="10"
           initialSize="10"

from the following list

```
    <Resource name="jdbc/scadalts"
          auth="Container"
          type="javax.sql.DataSource"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          testWhileIdle="true"
          testOnBorrow="true"
          testOnReturn="false"
          validationQuery="SELECT 1"
          validationInterval="30000"
          timeBetweenEvictionRunsMillis="30000"
          maxActive="80"
          minIdle="10"
          maxWait="10000"
          initialSize="10"
          removeAbandonedTimeout="1000"
          removeAbandoned="true"
          abandonWhenPercentageFull="75"
          logAbandoned="true"
          minEvictableIdleTimeMillis="30000"
          jmxEnabled="true"
          jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;
                                                        org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=1500)"
          username="root"
          password="root"
          driverClassName="com.mysql.jdbc.Driver"
          defaultTransactionIsolation="READ_COMMITTED"
          connectionProperties="useSSL=false;allowPublicKeyRetrieval=true"
          url="jdbc:mysql://database:3306/scadalts"
         />
```
I don't know exactly how to use them, I did several tests and finally left them with minidle=10 and maxactive=10 and it didn't change much, it continues to open 40 connections. If you can explain what can be improved, I would appreciate it.

2 - There are several customers that will be migrated to Scada-LTS, in ScadaBR, all were as different applications within the same tomcat server and within the same instance in AWS, example:
IP:8080/client1
IP:8080/client2
IP:8080/client3
...
In this update I intend to use each client in a different instance, I just tested it that way, but I noticed that when I clone the instance, the new instance opens 40 more connections. We are connecting with the SQL datasource on an RDS service, there it is more robust and supports 400 connections, but we will easily reach this, since there are already 12 clients on the old server.

Hence the question, what is the best approach thinking about the issue of open connections? Everything on the same server would change something for being the same IP or create more connections per application in the same way.

3 - Finally, a print of the list of connected users follows, strange that it opens several connections with the query "SELECT1" as in the context.xml file, but opens some queries with the select from the datasource itself, but only a few, because they are 85 datasources in total.
![image](https://user-images.githubusercontent.com/38673539/226446311-8782fffa-a090-4151-af5b-eec108211d89.png)

**Comment by Limraj** [comment]
Hi @fabiodurao,
1. The configuration you posted applies to mysql, not postgesql..
2. Unfortunately, there is something in tomcat that if you have something more than Scada-LTS/ScadaBR in webapps, it treats it as separate applications and applies the settings you enter in <context> separately to all applications, i.e. if outside of Scada-LTS you have e.g. docs and ROOT then you have to count these limits x3. The solution is to move the ROOT and the rest of the folders to another place, they are not needed for the operation of tomcat and Scada-LTS.

**Comment by fabiodurao** [comment]
I don't think I made myself understood, I'm already using the jndi resource in the sql datasources successfully, I've already made the connection in context.xml with postgresql, there are two "resources", one from the historian with mysql and another from the sql datasource . I had copied the context.xml from github in the post above just as a reference, but I'm sending below something close to what I did there (hiding credentials and ip).

```
    <Resource name="jdbc/WATER"
          auth="Container"
          type="javax.sql.DataSource"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          testWhileIdle="true"
          testOnBorrow="true"
          testOnReturn="false"
          validationQuery="SELECT 1"
          validationInterval="5000"
          timeBetweenEvictionRunsMillis="5000"
          maxActive="50"
          minIdle="10"
          maxWait="5000"
          initialSize="10"
          removeAbandonedTimeout="1000"
          removeAbandoned="true"
          abandonWhenPercentageFull="75"
          logAbandoned="true"
          minEvictableIdleTimeMillis="30000"
          jmxEnabled="true"
          jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;
                                                        org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=1500)"
          username="1234"
          password="123456"
          driverClassName="org.postgresql.Driver"
          defaultTransactionIsolation="READ_COMMITTED"
          connectionProperties="useSSL=false"
          url="jdbc:postgresql://ip:5432/WATER"
         />  
```

The communication worked perfectly, but we are looking more closely at the number of connections, it is still relatively high, around 40 open connections for 85 datasources, I have already made several changes in context.xml and it always results in something similar, the curious thing is that if I put maxActive with small values, like 10, it opens 30 connections like "SELECT 1" and opens 10 more the select from the datasource appearing in the query column, instead of appearing SELECT 1 (see the print of the previous post to understand) .

1 - Are there other parameters to change to improve this or is 40 the minimum number of connections? I ask this, because even disabling all datasources and restarting tomcat, it already opens the 40 waiting connections, then, if you enable the datasources, it only changes the queries that I mentioned earlier.

2 - I didn't understand what you meant by the issue of the root folder and docs and what is the relationship with this subject.
My question was if I put all clients as new applications within the same tomcat, if it would only use these 40 connections for all clients or would it open another 40 for each client. When I replicate instances in aws, each new instance opens 40 connections, not what we want.

**Comment by Limraj** [comment]
Hi @fabiodurao ,
what do you have in the CATALINA_HOME/webapps folder?


You should only have Scada-LTS there. If you have more folders, e.g. ROOT, docs and others, then Tomcat treats each such folder as a separate application and assigns` <Resource>` from context.xml to it, which means that if you have minIdle=10 limits, you need to multiply this parameter by the number of such applications in webapps. And this has the effect that the same connection pool is created for each such application. So if you only have Scada-LTS, it will be easier for you to adjust the configuration according to your needs. Generally, the parameters that are there should be enough for this (in `<Resource>`). If you only have Scada-LTS in your webapps and you still have this problem, it will try to help you adjust the configuration.

**Comment by fabiodurao** [comment]
It only has the ROOT folder and the ScadaBR/Scada-LTS application. I can even remove the ROOT folder if you want me to test it, but it is no longer hitting the (n_applications)x10 account

![image](https://user-images.githubusercontent.com/38673539/226646238-38697244-1594-48bf-a397-4bedb032fd77.png)

**Comment by Limraj** [comment]
1. ROOT you can move the directory higher so that it is only Scada-LTS.

2. Stop tomcat, see if all connections are terminated. (this may take a while)

3. I understand that you have one `<Resources>` defined with a field for postgresql?

4. When you do these things, take a screenshot with tomcat turned off, if there are any processes from the application, you need to close them, and then after starting the application, if you have changed the <Resource> configuration for postgresql, then also send a detailed configuration without ip address / logins / passwords.  
I'll move this `<Resource> `configuration to myself and see how it behaves.

5. You can also send an example SQL Data Source configuration in JSON. First of all, I mean what queries you call, what update you have set on Data Source. Earlier you wrote that you have 85 Data Sources. I'll see how it behaves with one such Data Source, and with more.

**Comment by fabiodurao** [comment]
1. ROOT folder moved.
2. Tomcat stop (before step 1) the open connections are practically only from two database management systems (mine and the client's that must be open there in his office).
![image](https://user-images.githubusercontent.com/38673539/226655110-5d8c564b-0e38-4ab0-979b-bdfafb54374e.png)

3. Yes, only one resource for history in mysql and one for jndi in postgresql

`<?xml version="1.0" encoding="UTF-8"?>
<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    
    <Resource name="jdbc/scadalts"
          auth="Container"
          type="javax.sql.DataSource"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          testWhileIdle="true"
          testOnBorrow="true"
          testOnReturn="false"
          validationQuery="SELECT 1"
          validationInterval="30000"
          timeBetweenEvictionRunsMillis="30000"
          maxActive="80"
          minIdle="10"
          maxWait="10000"
          initialSize="10"
          removeAbandonedTimeout="1000"
          removeAbandoned="true"
          abandonWhenPercentageFull="75"
          logAbandoned="true"
          minEvictableIdleTimeMillis="30000"
          jmxEnabled="true"
          jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;
                                                        org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=1500)"
          username="scadalts"
          password="XXXXX"
          driverClassName="com.mysql.jdbc.Driver"
          defaultTransactionIsolation="READ_COMMITTED"
          connectionProperties="useSSL=false"
          url="jdbc:mysql://localhost:3306/scadalts"
         />   
    <Resource name="jdbc/WATER"
          auth="Container"
          type="javax.sql.DataSource"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          testWhileIdle="true"
          testOnBorrow="true"
          testOnReturn="false"
          validationQuery="SELECT 2"
          validationInterval="5000"
          timeBetweenEvictionRunsMillis="5000"
          maxActive="20"
          minIdle="10"
          maxWait="5000"
          initialSize="10"
          removeAbandonedTimeout="1000"
          removeAbandoned="true"
          abandonWhenPercentageFull="75"
          logAbandoned="true"
          minEvictableIdleTimeMillis="30000"
          jmxEnabled="true"
          jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;
                                                        org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer;
                                                        org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=1500)"
          username="XXXXX"
          password="XXXXX"
          driverClassName="org.postgresql.Driver"
          defaultTransactionIsolation="READ_COMMITTED"
          connectionProperties="useSSL=false"
          url="jdbc:postgresql://IP:5432/WATER"
         />  
</Context>`

5. I'll send you prints of the connections opened after starting tomcat, I just ran the sql "select * from pg_stat_activity;". I can send you the json on staff to test the connections. The behavior remains the same after leaving only the "ScadaBR" folder in the webapps.

![image](https://user-images.githubusercontent.com/38673539/226661059-b795b5d9-300d-404f-9c52-2e3662aada64.png)

![image](https://user-images.githubusercontent.com/38673539/226661808-77c1dc08-f3b0-4501-b5d4-663310cad8c5.png)

I left the connections sorted by the origin of the connection, notice that it opens about 30 connections with "SELECT 2" (it was 1, I changed it to test if it was obeying the context.xml changes) and about 10 more connections that keep changing every time I update, it's as if he was pooling the 85 datasources in a rotational way using only these 10 connections that expose the select of the datasources. If I increase the parameter maxActive=40, they all stay as "SELECT 2", it still maintains 40 connections, but it doesn't expose any more select from any datasource.
