### ISSUE TITLE
Graphical Views cached aren't reload when cancel

### ISSUE THREAD

**Issue by Xt-Man** [SCADA-LTS/Scada-LTS#2457]
**Describe the bug**
On update a graphical view and click "Cancel" the cache still with the modifications

**To Reproduce**
1. Create a new Graphical View and save it
![img01](https://user-images.githubusercontent.com/39890311/210615915-45df8943-355c-4a00-9156-a23982b8c8d4.PNG)

2. Click on 'Edit View'
3. Change the position of a component 
![img02](https://user-images.githubusercontent.com/39890311/210616131-62fa163c-a84e-415f-b384-f3b4b3838d5f.PNG)
4. Click "Cancel"
5. The modifications aren´t rollbacked 
![img03](https://user-images.githubusercontent.com/39890311/210616262-d8ecb60c-f564-4b96-a498-a10aac3a34f5.PNG)

**Expected behavior**
Rollback the modifications

**Additional context**
My env.properties: view.cache.enabled=true
The modifications in cache don't affect the record in database, if i restart the tomcat the modifications in graphical view are gone.

Other situation: env.properties: view.cache.enabled=false
On cancel click the modifications are rollbacked - OK, but on save click the modifications aren't save

**Comment by Limraj** [comment]
If you want to check saving changes in the database, test the cache, then add/subtract the components view. What I wrote is not necessarily related to the cache or saving in the database, but only, for example, to the rendering of this object on view. If you write that something is not saved in the database, then check the database to see if it is actually not saved.
If what you write is true, it would mean some cosmic bugs. In such cases, it is worth checking exactly what is going on.

**Comment by Xt-Man** [comment]
I think I didn't explain it correctly.
The point is: edit a view, but don't save it, click cancel. The changes are still there.

**Comment by Limraj** [comment]
Each component has parameters x,y,z and it doesn't always work, maybe the problem is related to rendering this object in view. It doesn't have to have anything to do with the database or the cache.
To test the cache/database you have to add/subtract components on the view. Since you wrote that something may not work here, it's worth checking. However, the problem you are presenting is most likely related to rendering the object on the view, i.e. it is related to interpreting the x,y,z parameters, which would not be such a serious problem.

**Comment by Xt-Man** [comment]
I still think that is the Cache,
1) click edit
2) add a component
3) click Cancel
4) the added component still there

The record in database isn´t updated (correctly, i click cancel) but you can go to others pages, then go to graphical view and select that view, the added component still there.

Now restart tomcat, login and go to graphical views, select it, now the visualization is correct

i can upload a video on youtube and paste the link here

**Comment by Limraj** [comment]
Cache View replaced the field in the User that served as a cache, for it to work as in the older version, you need to enable the cache. It shouldn't be turned off. However, I will check how the cancel option worked in the older version (2.6.15). Maybe some changes have affected how it works now, or it's an old bug, in either case it needs to be fixed.

**Comment by Limraj** [comment]
Hi @Xt-Man,
As you determined it was related to the cache, after clicking cancel the memory state was not reset.
I've made some fixes and found other bugs and fixed: https://github.com/SCADA-LTS/Scada-LTS/pull/2458

This topic introduced problems: https://github.com/SCADA-LTS/Scada-LTS/pull/2443

I would be grateful if you check: opening different views in multiple tabs (with random point components to check if the view updates), creating, updating, deleting views.

Best wishes,
Kamil Jarmusik

**Comment by Xt-Man** [comment]
Hi @Limraj 

I'll check

Thank you

**Comment by Xt-Man** [comment]
Hi @Limraj ,

the cancel button issue was solved.

But i found a new bug.
1) Tab 1 - open view 1
2) Tab 2 - open view 2
3) click edit on view 1 and 2
4) add a component on view 1
5) add a component on view 2
6) click save - view 1
7) click save - view 2

only the component added on view 1 was saved

**Comment by Limraj** [comment]
Thanks @Xt-Man,
adding cache reset for cancel, broke standalone views editing (save one reset the state of the other if it was modified at the same time). Now it should be ok.

**Comment by Limraj** [comment]
There's another problem I need to solve.

**Comment by Limraj** [comment]
Hi @Xt-Man,
The main problem with our view editing mechanism is that the view update takes place in separate requests, so we need the state of this view in different places in this process, we can't do it in one request, which made the topic a bit complicated. I fixed all these issues, now it should behave as intended. There is one drawback, that is, you cannot edit the same view in one session at the same time. You can edit different views independently in one session, different views in different sessions, and edit one view but in different sessions. In general, it is much better than in the old version of the code, where it was not possible to edit two different views in one session, what's more, it was dangerous and it was easy to break something, because the state of one view was visible in the other view and saving would overwrite one view with the state second view. In addition, we have introduced separations of different views in one session, thanks to which we can open many views in different tabs and this does not cause problems with refreshing them.

Correct implementation of the mechanism of updating the view with new components should take place on the client side, and not create requests to the server to update the view state. However, such an improvement would require even more changes.

**Comment by Limraj** [comment]
@Xt-Man 
I also fixed NullPointerException for CompoundChild, added some unit tests.

**Comment by Limraj** [comment]
@Xt-Man let me know if you will test it.

**Comment by Xt-Man** [comment]
Hi @Limraj 
yes i'll test it

**Comment by Limraj** [comment]
How will you test it best on different components, including setting values ​​on views. (settable points, and 'simple point' component with checked 'display control')

**Comment by Xt-Man** [comment]
Hi @Limraj ,
i finished the tests, it seems ok to me.
Thanks

Should i close this issue?

**Comment by Limraj** [comment]
@Xt-Man Thanks for tests.
Yes you can close.
