### ISSUE TITLE
The fatest way to disable fullscreen warning text

### ISSUE THREAD

**Issue by AndreLuisSilva** [SCADA-LTS/Scada-LTS#2478]
Hello, I'm migrating a project from ScadaBR 1.2 to the ScadaLTS v2.6.18 version, and I realized some things that had already been implemented in ScadaBR that can be added in the future in ScadaLTS, one of them is the option to disable the "Ctrl + Shift + F" that appears every time the page is updated, in ScadaBR there is a variable inside the views.jsp file where it is possible to enable and disable, if there is a check box somewhere in the future that enables and disables it, it would be more intuitive for the end user, and also the possibility of enabling the "padding 0" of the graphic view to remove the upper border when it is left in full screen with the F11 key, in ScadaBR I would insert a style="padding: 0px;" in the "mainContent" div, now in ScadaLTS I needed to add this padding to the "sltsContent" div and even then a small border still remained when in full screen, and with that I realized that it was necessary to add one more style=padding: 0px inside a table in the views.jsp file, I also added a style="overflow: hidden;" inside the html tag in the page.tag file so that the scroll bar disappears to leave ScadaLTS in fullscreen, this is the only way I managed to make the ScadaLTS screen the same as ScadaBR and manage to migrate my platform project, I will attach some images to show the before and after the changes I made so you can understand how it turned out.

Without the changes
![Captura de Tela (43)](https://user-images.githubusercontent.com/12211629/224342974-17b1d0a8-63d4-471f-b61b-0b6bab70020d.png)

Message that appears every time the page is refreshed
![Captura de Tela (42)](https://user-images.githubusercontent.com/12211629/224343229-067902f6-ba78-443d-a633-89a71057f990.png)

After the changes
![Captura de Tela (40)](https://user-images.githubusercontent.com/12211629/224344443-4cdba040-651e-414e-9249-22521d91bc06.png)

**Comment by Limraj** [comment]
Hi @AndreLuisSilva,
You can suggest specific changes in the pull request.

Regards,
Kamil Jarmusik

**Comment by fabiodurao** [comment]
Hello Limraj, I asked him to report the modification he made, because in ScadaBR we already had a padding of 5px that we didn't like and we always took it off in projects, but before it was just changing the page.tag file and resetting the padding, now there are a few more changes needed.

1 - The suggestion would be to remove the pading or the white border around the representations. We do all this to be able to create an image, for example, with 1920x1050 to be used in full screen (from scada-lts and the browser) in a 1920x1080 resolution (discounting 30px to maintain copyright) and to be able to fully frame the graphic representation on the screen without having to use scroll bar;

2 - Taking advantage of this, the native scrollbar is a little hidden and I often need to resize the page to be able to see something if it is not in fullscreen, it could just be the css of the scrollbar. In parallel, the colleague had to remove the scroll bar in the css even with the screen in fullscreen to be able to frame the screen 100%;

3 - The text "Press ctrl+shift+f to exit fullscreen" is great for those who are new to the system, but when we put a project into production to be used in fullscreen, this text gets in the way a lot, because it takes up more space and because it fades out 10 seconds later. As we usually don't want the user to leave fullscreen and navigate only through the links we create, we usually remove this text by changing views.jsp . I believe that a simpler approach would be to add a checkbox on the scada-lts settings screen with the text "don't display the instruction to exit fullscreen".

**Comment by Limraj** [comment]
Hi @AndreLuisSilva and @fabiodurao ,
I think I met all the requirements:
1. There is a checkbox to select if you want to see a message with a shortcut to disable full screen mode - it is unchecked by default;
2. Refreshing the page does not show this shortcut again;
3. For fullscreen mode, I set the padding to 0px, now the fullscreen view starts and ends before the copyright footer, there are no empty spaces.

fixes will be included in the next version 2.7.5.3

@fabiodurao I would appreciate if you could test it: 
https://github.com/SCADA-LTS/Scada-LTS/pull/2514

**Comment by Limraj** [comment]
Hi @fabiodurao and @AndreLuisSilva,
The last form of this function:

1. Ability to set the following options in the user:
a) Enable full screen mode - if it is set to true, and there is at least one view, then if the user enters Graphical Views, it forces full screen mode, each user can disable it with a shortcut;
b) Hide shortcut to disable full screen - disables the shortcut when switching to full screen;
Old ui:
login as admin:
![Screenshot 2023-05-02 at 12 04 05](https://user-images.githubusercontent.com/35842300/235638343-2ebc0844-6c2d-496a-b699-7587120dd4a8.png)
login as non-admin:
![Screenshot 2023-05-02 at 12 04 33](https://user-images.githubusercontent.com/35842300/235638442-59188a3a-c141-4077-a3ec-d6dc4fa30220.png)
New ui:
login as admin:
![Screenshot 2023-05-02 at 12 06 07](https://user-images.githubusercontent.com/35842300/235638782-7230fdc6-05b7-48e4-a4f7-5d24a2e25cef.png)
login as non-admin:
![Screenshot 2023-05-02 at 12 05 32](https://user-images.githubusercontent.com/35842300/235638666-6ea05bab-6559-4908-9089-f3c0a720a14d.png)

2. Possibility to force setting in System Settings, only admin can do it:
a) Force full screen mode - setting this option forces all users to full screen mode, additionally, a normal user cannot return to normal mode, an admin can and the "Enable full screen mode" checkbox in the user is greyed out and the user cannot change his state , after hovering over the checkbox, information appears about the reason for this state;
b) Hide shortcut to disable full screen - this forces all users to have no shortcut visibility, the "Hide shortcut to disable full" option in the user is greyed out, after hovering over the checkbox there is information about what this state is due to; 
Old ui (System Settings):
![Screenshot 2023-05-02 at 12 08 44](https://user-images.githubusercontent.com/35842300/235639310-9b5c5af7-9233-49a0-88ae-73daf532a18f.png)
New ui (System Settings):
![Screenshot 2023-05-02 at 12 07 25](https://user-images.githubusercontent.com/35842300/235639034-621c4644-2a92-43b0-a5d8-fec8c3a90b9c.png)

Regards,
Kamil Jarmusik
