### ISSUE TITLE
Basic auth by HTTPS for API httpds 

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2533]
**Description**
One of the uses of this api is to connect several Scada-LTS instances, a convenient way to authenticate clients of this api should be added. 

**Reproduce**
1. [Configuration of HTTPS communication for Tomcat](https://github.com/SCADA-LTS/Scada-LTS/wiki/Configuration-of-HTTPS-communication-for-Tomcat)
2. Login as admin;
3. Create non-admin user as 'httpds_user', set Password: user;
4. Create Data Source 'HTTP receiver' as rec_ds_1 (enable), and create Data Point as rec_dp_1 ('Data type': numeric, 'HTTP parameter name': temp, enabled);
5. Create Virtual Data Source as vir_ds_1 (enable, update: 1s), and create Data Point as vir_dp_1 (Change Type: Brownian, min: 1, max: 40, min change: 0.2, start value: 23, enabled)
6. Create publisher 'Http Sender' as pub_1 (method: GET, url: https://127.0.0.1:8443/ScadaBR/httpds, Credentials: Username: httpds_user, Password: user, enabled)
7. Click on 'Send static data':
![Screenshot 2023-05-09 at 00 49 56](https://user-images.githubusercontent.com/35842300/236954123-3d6347fa-0688-4d54-a4fc-47c180b3d8a8.png)
if result is '(no response data)' then ok;
8. Select point 'vir_ds_1 - vir_dp_1' and click 'Add';
9. Change 'Parameter name' on 'temp', and click in Status column in enable;
10. Go to 'Watchlists', and create WatchLists as wl_1 with points: 'rec_ds_1 - rec_dp_1', 'vir_ds_1 - vir_dp_1', if both points change simultaneously, it works ok;

**Comment by fabiodurao** [comment]
I'm trying to replicate the tutorial but without success.

- Step 2 says that you need to create a user with the name "httpds_user", but in version 2.7.5.3 there is already a user "httpds-basic", I imagine you are referring to it. This user is disabled by default, I just enabled it. I did tests with this user linked to the "user profile" that had full access to the datasources of the variable that was being published and with access to the datasource of the variable that I was receiving, I also did tests unlinking the user profile.

- This feature worked on ScadaBR without the need for authentication, but the url was
http://127.0.0.1:8080/ScadaBR/httpds
now the url is
https://127.0.0.1:8443/Scada-LTS/httpds

changed port 8080 to 8443 and went from http to https, as I understand it is related to authentication and the SSL certificate installed for this service.

I did tests sending to localhost and 127.0.0.1, the windows firewall is disabled, I don't have other firewall/antivirus installed and with the same network and firewall settings this worked on ScadaBR.

If you can help me figure out what the problem is, I'd appreciate it.

![publisher](https://github.com/SCADA-LTS/Scada-LTS/assets/38673539/23e8fb1b-bc25-431b-8596-2a23867a8ac7)
