### ISSUE TITLE
I'm confused about the license, so I'm asking.

### ISSUE THREAD

**Issue by wjinens-common** [SCADA-LTS/Scada-LTS#2541]
If I create a project with this program, license contagion does not occur for that?

**Comment by Limraj** [comment]
Hi @wjinens-common,
License is valid: GPL-2.0 license (in most projects on github, on the main project page, there is information about the license, note not all projects on github have this license, even open-source projects may have different licenses, e.g. MIT, Apache License 2)

Basic assumptions of this license:
1. freedom to run the program for any purpose (freedom 0)
2. freedom to analyze how the program works and adapt it to your needs (freedom 1)
3. freedom to distribute an unmodified copy of a program (freedom 2)
4. the freedom to improve the program and distribute your improvements publicly so that the whole community can benefit from them (freedom 3)

[If I use a piece of software that has been obtained under the GNU GPL, am I allowed to modify the original code into a new program, then distribute and sell that new program commercially?](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html.en#TOCGPLCommercially)
You are allowed to sell copies of the modified program commercially, but only under the terms of the GNU GPL. Thus, for instance, you must make the source code available to the users of the program as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL.
These requirements are the condition for including the GPL-covered code you received in a program of your own.

Let me know if this cleared your doubts.

Links:
[gpl-2.0-faq](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html.en)

Regards,
Kamil Jarmusik

**Comment by wjinens-common** [comment]
thank you for reply
I think i misunderstood the question.
It is not the source code for Scada-LTS.
I wanted to explain the code for the graphics page on running Scada-LTS.
Is license transmission occurring in JavaScript code on the graphics page?

**Comment by Limraj** [comment]
Hi @wjinens-common,
Then write what would you like to achieve? Maybe it will be easier to understand what you mean.

This license talks about the distribution of the application, its source code. I think the particular configuration inside the application is more of a service and it is no longer under this license. That is, the source code of the configuration does not have to be available to the client, etc. 

Regards,
Kamil Jarmusik
