### ISSUE TITLE
Point locator test in Modbus IP blocked after bad configuration choice

### ISSUE THREAD

**Issue by nduvernois** [SCADA-LTS/Scada-LTS#2782]
In a Modbus IP source, select:
- Register range = Coil status
- Modbus datatype = 2 byte unsigned integer
- Offset = whatever
and click on read. An error message is displayed "only binary values can be read from Coil and input ranges", which is fine.
Then click OK on this message.
The "Read" button is now greyed and cannot be used any longer. It is necessary to refresh the page in order to recover the functionnality.

Proposed solution:
If "coil status" and "input status" work only with binary data, why is the choice of Modbus data type possible ? -> once "Coil status" or "input status" is selected, deactivate the "Modbus data type" field, and reactivate it if "Holding register" or "Input register" is selected
I have not checked for other datasources, but a similar problem may exist
 
 - OS: Windows Server 201610.0
 - Browser: Chrome 118
 - Version: 2.6.18

**Comment by fabiodurao** [comment]
Hello, this issue has already been reported in the following link:
https://github.com/SCADA-LTS/Scada-LTS/issues/2528

The problem of the "read" button being unavailable did not happen to me in any test.

As for the issue of data types, as reported, the issue is that this field is refreshed only when the "register range" option is changed, by default, when opening the screen it gives a wrong impression, but if you change it to holding register and return to coil, you will notice that the "data type" option will be unavailable, again this happens because this field is only updated when there is an option change in the "register range".

This type of refresh problem also happens in the virtual data source when we are creating an attractor datapoint, it uses another datapoint as a reference, but the first time no datapoint appears, it is necessary to create the attractor datapoint with an empty reference, save the datapoint, refresh the page, edit the datapoint and then select the reference datapoint to use it.

I will suggest what has already been suggested to me. I noticed that you opened a lot of issues in the last few days, it would be more productive if you researched the existence of issues before opening a new one, because as seen, the last two have already been reported, the last one has not yet been fixed, but the previous one has, I understand that it is using the "latest" version, but some fixes are already coming in versions not yet tagged as "latest", it might make sense to upgrade. I personally use the most recent version in all my projects and I test it while I am developing the project, to make sure it is meeting what I need, after knowing a version well, when the next update comes out, you only need to test the new or fixed features.

I hope I can help you make the most of the tool and contribute to the project.

**Comment by Limraj** [comment]
Hi @fabiodurao,

@nduvernois He's waiting for a new version, everything's fine.

Regards,
Kamil Jarmusik
