### ISSUE TITLE
datasource activation gives error message

### ISSUE THREAD

**Issue by nduvernois** [SCADA-LTS/Scada-LTS#3020]
On a given datasource already present & active, try to activate it or deactivate it. An error window pops up with message : "Incorrect result size: expected 1, actual 0"
the attached file shows a part of file stdout logfile.
[error_message_activate.txt](https://github.com/user-attachments/files/17116631/error_message_activate.txt)
When it appears, the datasource state is not toggled. After some page refresh, it may finally succeed.

 - OS: Windows Server 2016
 - Browser : Chrome 129
 - Version: v2.7.7.3_For build 3789793776

**Comment by Limraj** [comment]
Hi @nduvernois,

This is because the database events have been removed. In version 2.8.0 this error will no longer occur here, because in this version we do not retrieve the event from the database this place. However, it is worth securing the service that retrieves the events, in such a case, this will also be corrected in version 2.8.0.

Regards.
