### ISSUE TITLE
Unable to export project from SCADALTS

### ISSUE THREAD

**Issue by TomyZacharia** [SCADA-LTS/Scada-LTS#465]
We have a fairly large project, which we are in the process of migration from ScadaBR 0.9. We finally managed to migrate by following the procedure as follows.
1. Exporting only Watch lists, Graphical views, Data sources and Data points. 
2. Create users in SCADALTS with same names manually. (Also works by making all users administrators prior to export)
3. We had to manually copy and change permissions for Graphics and Uploads folders.
4. Import the JSON file created in step 1. (Alternatively change users from "administrators" to normal)
![6](https://user-images.githubusercontent.com/35994183/36141958-adcb66d6-10cc-11e8-8b84-d5b6b6e14716.jpg)

The problem we are facing is of export project from the SCADALTS project. We are getting the attached error screen whenever we carry out an export.
![7](https://user-images.githubusercontent.com/35994183/36141959-ae2088b4-10cc-11e8-8f0d-23deac6ac1ea.jpg)
 
The export works if all the users are made "Admin" users.

We are using ubuntu 16.04, Tomcat 7, mysql 5.7 and openjdk 1.8. SCADA LTS v.0.0.9

**Comment by grzesiekb** [comment]
###  It is quite a big topic that requires designing and simplification in my opinions.

  * The import and export mechanism  based on an external library to which we don't have source which causes many problems.
  * Another surprise is that it is not possible to operate on the database, because the data is stored in blobs that are serialized.
  * No security of data inconsistencies resulting from the use of id and Xid.

E.g
Separating individual modules and then preparing data export with their own REST API and databases (designed in accordance with art).

**Comment by SoftQ** [comment]
Hello Tomy
Thank You for feedback. At present we are working on fixing datapoint hierarchy export/import. In case You have any needs or additional questions please don't hesitate to write us email to info@scada-lts.org
